### ISSUE TITLE
It's hard to understand the readme file.

### ISSUE THREAD

**Issue by ziad9267** [Syntrait/splinux#3]
It's not a real issue but it's hard for me to understand the readme file, especially in "How to run the games" part, Can you make a tutorial or give more examples to understand it ?

**Comment by Syntrait** [comment]
I agree, I should probably make the readme file more readable. It's my first time publishing a project, and writing documentation for it, so excuse me for the confusion. I should probably use the Wiki feature of GitHub, because other projects use it to write guides.

In a nutshell,

Steam's DRM prevents us from starting the same twice.
Goldberg is a Steam emulator that makes the game think that the game is being ran from Steam.

```libsteam_api.so``` or ```steam_api64.dll``` is a library used by all Steam games, and it's responsible for communicating with Steam. Since we are running the second (or the consequent) game outside of Steam, we have to make sure it doesn't communicate with Steam. If it does communicate, then Steam will say "You can't launch the same game twice". That's why we replace it, so it doesn't communicate with Steam.

The lock file (which doesn't exist for all games), is a file that some games create to see if they have already been opened. Yes, some games (especially Unity games) also check if they are running twice, too, along with Steam.

I think the most confusing part is bubblewrap (bwrap)

bwrap allows you to fool the game. When the game tries to write to the usual save data location, bwrap instead makes it write it elsewhere.
1. Game2 tries to write to ```/home/user/savefile```
2. bwrap fools the game, and actually makes it write to ```/home/user/savefile2```
3. Game2 thinks it wrote to ```/home/user/savefile```, but that's not the case
4. Now, the first game uses ```/home/user/savefile```, and the second game uses ```/home/user/savefile2``` for the save data location

If you have any other questions, or you didn't understand a part, feel free to ask it. I'd be glad to explain it, and make it more understandable for people in the future.

**Comment by ziad9267** [comment]
No problem it happens to best of us, But i have another question about running the game in proton, There's a command that you say run the game with it, How can i use it should i write it in the app or something like that ?

I'm sorry for the question if it has a bit of stupid.

**Comment by Syntrait** [comment]
No problem, it's a good question, and I'm happy to help.

In step 4, we opened a terminal, at the location of the game. You should run that command in that terminal.

At the moment, the program only handles the binds of the the inputs to the game, that's why it's this complicated and tiring. If I make the program handle all of this automatically, everything would be much clearer.
